### ISSUE TITLE
Add Comment Content to Activity Page

### ISSUE THREAD

**Issue by jonaylor89** [InTheLoopStudio/pangolin#6]
**Is your feature request related to a problem? Please describe.**
When a user receives a comment, they can only see _who_ commented and not _what_ was commented on the activity page

**Describe the solution you'd like**
On the activity page, when a user sees who commented (or liked) on their post, it should also tell them the comment content and the loop title.

**Additional context**

The text should say something like: `User1 commented 'blah blah blah' on your loop 'loop title here'`

**TODO:**
- [ ]  Add loopId to activities table for likes and comments
- [ ]  Update push notification cloud function
- [ ]  Update activity user_tile to get the comment content and loopId
